#!/usr/bin/env python3
"""Regenerates lib/moderation/text/unicode_fold_table.g.dart.

The fold table is derived from the Unicode Character Database shipped with the
running CPython (`unicodedata`). For every non-ASCII code point whose NFKD
compatibility decomposition, case fold, and combining-mark strip yields only
ASCII letters/digits/spaces, we record the folded form. This is the
compatibility-folding half of the matcher skeleton (fullwidth forms, math
alphanumerics, circled/superscript forms, Latin diacritics, ligatures, ...).

Cross-script visual confusables (Cyrillic/Greek/Armenian lookalikes) are NOT
in the UCD compatibility data and are curated by hand in
`lib/moderation/text/confusables.dart`.

Run from the repository root:

    python3 tool/moderation/generate_unicode_fold_table.py

Deterministic: output depends only on the Python version's UCD. The UCD
version is written into the file header so a regeneration diff is reviewable.
"""

import sys
import unicodedata
from pathlib import Path

MAX_CP = 0x30000
TARGET = Path("apps/mobile-flutter/lib/moderation/text/unicode_fold_table.g.dart")


def fold(ch: str) -> str:
    s = unicodedata.normalize("NFKD", ch).casefold()
    return "".join(c for c in s if unicodedata.category(c) not in ("Mn", "Me"))


def main() -> int:
    entries: dict[int, str] = {}
    for cp in range(MAX_CP):
        ch = chr(cp)
        if ch.isascii():
            continue
        s = fold(ch)
        if not s:
            continue
        if all(c.isascii() and (c.isalnum() or c == " ") for c in s):
            if s == " ":
                s = " "
            entries[cp] = s

    lines = []
    lines.append("// GENERATED FILE - DO NOT EDIT BY HAND.")
    lines.append("//")
    lines.append(
        f"// Generated by tool/moderation/generate_unicode_fold_table.py from UCD {unicodedata.unidata_version}."
    )
    lines.append("// © Unicode, Inc. Used under the Unicode License v3.")
    lines.append(
        "// Maps a non-ASCII code point to an ASCII NFKD/case-fold skeleton for"
    )
    lines.append(
        "// evasive-text matching. Curated cross-script lookalikes live in"
    )
    lines.append("// confusables.dart.")
    lines.append("")
    lines.append("/// Non-ASCII -> ASCII compatibility fold. Built once at startup.")
    lines.append("const Map<int, String> kUnicodeFoldTable = <int, String>{")
    for cp in sorted(entries):
        value = entries[cp]
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  0x{cp:X}: '{escaped}',")
    lines.append("};")
    lines.append("")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET} with {len(entries)} entries (UCD {unicodedata.unidata_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
